import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Banner from '../components/Banner'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Project from '../components/Project'
import ScrollBtn from '../components/ScrollBtn'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio | Nipun Mitra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <About />
      <Skills />
      <ScrollBtn />
      <Project />
      <Experience />
      <Contact />
      <Footer />

    </div>
  )
}
